apiVersion: v1
kind: Service
metadata:
  name: grpc-beer-gateway
spec:
  selector:
    app: grpc-beer-gateway
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8090
      targetPort: http