apiVersion: v1
kind: Service
metadata:
  name: grpc-beer-nginx
spec:
  selector:
    app: grpc-beer-nginx
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8888
      targetPort: http
