apiVersion: v1
kind: Service
metadata:
  name: grpc-beer-envoy
spec:
  selector:
    app: grpc-beer-envoy
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8091
      targetPort: http